### ISSUE TITLE
Detect "No changes. Infrastructure is up-to-date."

### ISSUE THREAD

**Issue by jamesgoodhouse** [lifeomic/terraform-plan-parser#19]
It would be great if the tool could detect when there are no changes to be made so you could programmatically key off of this to decide if to run apply or not.

**Comment by smazurov** [comment]
terraform plan has [exit codes](https://www.terraform.io/docs/commands/plan.html#detailed-exitcode) for this.

**Comment by jamesgoodhouse** [comment]
Well shoot, I didn’t know that. Thanks for the info!

**Comment by mdlavin** [comment]
I ran into a similar issue and I think it would be nice if the tool detected the 'No changes' case from the output. Without support for that, the caller will need to do two levels of checking first the status code and then using this tool. Having it check just the output would be convenient for me.
