### ISSUE TITLE
Error Generating output

### ISSUE THREAD

**Issue by riponbanik** [lifeomic/terraform-plan-parser#2]
Running the command 'parse-terraform-plan --pretty -i output.stdout -o output.json' shows the error below. Using terraform 0.11.1

C:\Users\xx\AppData\Roaming\nvm\v6.10.0\node_modules\terraform-plan-parser\src\cli.js:10
async function readFromStdin() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by mdlavin** [comment]
It looks like you are running an old version of node. The `parse-terraform-plan` requires the current LTS, v8

**Comment by philidem** [comment]
@riponbanik if you don't have flexibility to use to use the latest Node.js runtime you can use `babel-register` which will transpile the code when it is loaded at runtime. See https://babeljs.io/docs/usage/babel-register/

Also, see https://github.com/babel/babel/tree/master/packages/babel-preset-env which makes it easier to target babel for a specific version of node.

**Comment by riponbanik** [comment]
@mdlavin and @philidem Thanks Guys. I have updated to node 8.9.4

It resolved the error, but output does not show the resources to be created -

{
  "errors": [
    {
      "code": "UNABLE_TO_FIND_STARTING_POSITION_WITHIN_STDOUT",
      "message": "Did not find magic starting string: \nTerraform will perform the following actions:\n"
    }
  ],
  "changedResources": [],
  "changedDataSources": []
}

And my input is like the following. I am using terraform version 0.11.1 and on windows 10 platform.

[0m[1mRefreshing Terraform state in-memory prior to plan...[0m
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
[0m
[0m[1mdata.aws_kms_alias.lambda: Refreshing state...[0m
[0m[1mdata.aws_iam_role.as_dynamodb: Refreshing state...[0m
[0m[1mdata.aws_caller_identity.default: Refreshing state...[0m

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  [32m+[0m create
[0m
Terraform will perform the following actions:

[32m  [32m+[0m [32maws_dynamodb_table.test
[0m      id:                        <computed>
      arn:                       <computed>
      attribute.#:               "1"
      attribute.3206617783.name: "Name"
      attribute.3206617783.type: "S"
      hash_key:                  "Name"
      name:                      "test"
      read_capacity:             "5"
      stream_arn:                <computed>
      stream_label:              <computed>
      stream_view_type:          <computed>     
[0m
[0m
[0m[1mPlan:[0m 1 to add, 0 to change, 0 to destroy.[0m

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

**Comment by philidem** [comment]
@riponbanik I suspect that the issue is due to the line end character sequence on windows. Linux/MacOS uses a single `\n` and Windows uses a `\r\n`. I forget about Windows sometimes. Let me see if I modify the code to be allow for `\r\n` or `\n`.

**Comment by philidem** [comment]
I normalize the input by replacing CRLF with LF before parsing starts using this code:

```javascript
logOutput = stripAnsi(logOutput).replace(/\r\n/g, '\n');
```
I added test case and published `terraform-plan-parser@1.0.11`. Please let me know if this fixes the problem.

Thanks!

**Comment by riponbanik** [comment]
@philidem, thanks but same issue.

+ terraform-plan-parser@1.0.11
updated 1 package in 6.748s

**Comment by midacts** [comment]
I'm running into this on Windows as well.

It seems to only happen when `terraform plan` does not show any changes.

`terraform-plan-parser@1.5.0`
