### ISSUE TITLE
Plan parsing support for Terraform v0.12 

### ISSUE THREAD

**Issue by avallecillac** [lifeomic/terraform-plan-parser#29]
Today Hashicorp has released the latest version of Terraform, v0.12, which includes drastic changes in the terraform plan output. Are there any plans on supporting this in the next releases of terraform-plan-parser?

**Comment by mbowen13** [comment]
@avallecillac 
In TF v0.12 and above there is built-in functionality to create a json file. 
```terraform show -json tf.binary > tf.json```

**Comment by avallecillac** [comment]
I checked it. I think it will be better to stick to their own official json format.
Thanks.
