### ISSUE TITLE
0.12.3 output seems to be broken. UNABLE TO PARSE

### ISSUE THREAD

**Issue by munntjlx** [lifeomic/terraform-plan-parser#30]
I was using terraform 0.12.x and get the following:

`{
  "errors": [
    {
      "code": "UNABLE_TO_PARSE_LINE",
      "message": "Unable to parse \"  # aws_instance.kaeptn-eichhorn will be created\" (ignoring)"
    },
    {
      "code": "UNABLE_TO_PARSE_CHANGE_LINE",
      "message": "Unable to parse \"  + resource \"aws_instance\" \"kaeptn-eichhorn\" {\" (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + ami                          = \"ami-13b8337c\"\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + arn                          = (known after apply)\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + associate_public_ip_address  = (known after apply)\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + availability_zone            = (known after apply)\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + cpu_core_count               = (known after apply)\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + cpu_threads_per_core         = (known after apply)\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + get_password_data            = false\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + host_id                      = (known after apply)\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + id                           = (known after apply)\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + instance_state               = (known after apply)\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + instance_type                = \"t2.micro\"\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + ipv6_address_count           = (known after apply)\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + ipv6_addresses               = (known after apply)\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + key_name                     = (known after apply)\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + network_interface_id         = (known after apply)\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + password_data                = (known after apply)\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + placement_group              = (known after apply)\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + primary_network_interface_id = (known after apply)\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + private_dns                  = (known after apply)\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + private_ip                   = (known after apply)\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + public_dns                   = (known after apply)\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + public_ip                    = (known after apply)\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + security_groups              = (known after apply)\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + source_dest_check            = true\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + subnet_id                    = (known after apply)\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + tenancy                      = (known after apply)\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + volume_tags                  = (known after apply)\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + vpc_security_group_ids       = (known after apply)\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + ebs_block_device {\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "UNABLE_TO_PARSE_LINE",
      "message": "Unable to parse \"          + delete_on_termination = (known after apply)\" (ignoring)"
    },
    {
      "code": "UNABLE_TO_PARSE_LINE",
      "message": "Unable to parse \"          + device_name           = (known after apply)\" (ignoring)"
    },
    {
      "code": "UNABLE_TO_PARSE_LINE",
      "message": "Unable to parse \"          + encrypted             = (known after apply)\" (ignoring)"
    },
    {
      "code": "UNABLE_TO_PARSE_LINE",
      "message": "Unable to parse \"          + iops                  = (known after apply)\" (ignoring)"
    },
    {
      "code": "UNABLE_TO_PARSE_LINE",
      "message": "Unable to parse \"          + snapshot_id           = (known after apply)\" (ignoring)"
    },
    {
      "code": "UNABLE_TO_PARSE_LINE",
      "message": "Unable to parse \"          + volume_id             = (known after apply)\" (ignoring)"
    },
    {
      "code": "UNABLE_TO_PARSE_LINE",
      "message": "Unable to parse \"          + volume_size           = (known after apply)\" (ignoring)"
    },
    {
      "code": "UNABLE_TO_PARSE_LINE",
      "message": "Unable to parse \"          + volume_type           = (known after apply)\" (ignoring)"
    },
    {
      "code": "UNABLE_TO_PARSE_LINE",
      "message": "Unable to parse \"        }\" (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + ephemeral_block_device {\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "UNABLE_TO_PARSE_LINE",
      "message": "Unable to parse \"          + device_name  = (known after apply)\" (ignoring)"
    },
    {
      "code": "UNABLE_TO_PARSE_LINE",
      "message": "Unable to parse \"          + no_device    = (known after apply)\" (ignoring)"
    },
    {
      "code": "UNABLE_TO_PARSE_LINE",
      "message": "Unable to parse \"          + virtual_name = (known after apply)\" (ignoring)"
    },
    {
      "code": "UNABLE_TO_PARSE_LINE",
      "message": "Unable to parse \"        }\" (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + network_interface {\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "UNABLE_TO_PARSE_LINE",
      "message": "Unable to parse \"          + delete_on_termination = (known after apply)\" (ignoring)"
    },
    {
      "code": "UNABLE_TO_PARSE_LINE",
      "message": "Unable to parse \"          + device_index          = (known after apply)\" (ignoring)"
    },
    {
      "code": "UNABLE_TO_PARSE_LINE",
      "message": "Unable to parse \"          + network_interface_id  = (known after apply)\" (ignoring)"
    },
    {
      "code": "UNABLE_TO_PARSE_LINE",
      "message": "Unable to parse \"        }\" (ignoring)"
    },
    {
      "code": "ORPHAN_ATTRIBUTE_LINE",
      "message": "Attribute line \"      + root_block_device {\" is not associated with a data source or resource (ignoring)"
    },
    {
      "code": "UNABLE_TO_PARSE_LINE",
      "message": "Unable to parse \"          + delete_on_termination = (known after apply)\" (ignoring)"
    },
    {
      "code": "UNABLE_TO_PARSE_LINE",
      "message": "Unable to parse \"          + iops                  = (known after apply)\" (ignoring)"
    },
    {
      "code": "UNABLE_TO_PARSE_LINE",
      "message": "Unable to parse \"          + volume_id             = (known after apply)\" (ignoring)"
    },
    {
      "code": "UNABLE_TO_PARSE_LINE",
      "message": "Unable to parse \"          + volume_size           = (known after apply)\" (ignoring)"
    },
    {
      "code": "UNABLE_TO_PARSE_LINE",
      "message": "Unable to parse \"          + volume_type           = (known after apply)\" (ignoring)"
    },
    {
      "code": "UNABLE_TO_PARSE_LINE",
      "message": "Unable to parse \"        }\" (ignoring)"
    },
    {
      "code": "UNABLE_TO_PARSE_LINE",
      "message": "Unable to parse \"    }\" (ignoring)"
    }
  ],
  "changedResources": [],
  "changedDataSources": []
}`

**Comment by munntjlx** [comment]
ignore

**Comment by bedge** [comment]
@munntjlx what was the issue? I'm seeing the same thing.
